version: '3.8'  # Pode remover esta linha conforme o warning

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  tests:
    image: ppodgorsek/robot-framework:latest
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./tests:/opt/robotframework/tests  # Mapeamento correto
      - ./results:/opt/robotframework/results
    environment:
      ROBOT_OPTIONS: --outputdir /opt/robotframework/results